### ISSUE TITLE
개발기간 내 개발환경 업데이트

### ISSUE THREAD

**Issue by ILoveGameCoding** [UOF2021/U.O.F-Mobile#10]
### 현재 개발 환경
> **Android Studio**
> - Android Studio Arctic Fox | 2020.3.1
> - Build #AI-203.7717.56.2031.7583922, built on July 27, 2021
> - Runtime version: 11.0.10+0-b96-7249189 amd64
> - VM: OpenJDK 64-Bit Server VM by Oracle Corporation
>
>
> **Gradle**
> - Android Gradle Plugin Version: 7.0.0
> - Gradle Version: 7.0.2
> - Gradle JDK: 11 version (11.0.10)
> 
> 
> **Android SDK**
> - Android 9.0(Pie) API Level 28
> - Android 6.0(Marshmallow) API Level 23

### 개발환경 업데이트 시 장단점
> **장점**
> - 최신화된 버전으로 성능 및 보안에 최적화된 기능 이용 가능
> - IDE 업데이트로 더 편리한 기능 사용 가능
> 
> 
> **단점**
> - 업데이트 후 새로운 버전으로 Pull 및 Push 할 때 개발자 환경에 따라 오류 발생 가능
> - 모든 개발자가 각자 업데이트 진행

개발기간 내에 Android Studio 업데이트가 있을 때 업데이트 후 진행할 건지, 아니면 최초 개발환경대로 진행할 건지 선택 필요

**Comment by ILoveGameCoding** [comment]
나는 최초 프로토타입이 나올 때까지는 개발환경 업데이트 안하고 유지하는 쪽이 관리하는데 편할 것 같음.  

만약 A PC에서는 업데이트가 성공했는데 B PC에서는 업데이트가 일부분만 성공하고 오류가 발생하면 서로 환경이 다른 상태가 됨. 그러면 해당 부분 때문에 Pull, Push, Merge할 때  생기는 문제 수정하는데도 시간이 들 것 같음. 어때?

**Comment by westofsky** [comment]
그러면 현재 개발환경 그대로 쭉 개발 후 마지막에 업데이트하고 마무리 수정작업 들어가는걸로 하시나요 ?

**Comment by ILoveGameCoding** [comment]
네. 일단 링크된 PR에 있는 부분까지만 Android Studio 업데이트 진행하고, 이후로는 개발환경 업데이트는 하지 않는 방향으로 하죠.

**Comment by le-la** [comment]
확인했습니다.
