### ISSUE TITLE
[U.O.F-Mobile] Activity 및 송수신 데이터

### ISSUE THREAD

**Issue by ILoveGameCoding** [UOF2021/U.O.F-Mobile#11]
# 필요 기능 및 송수신 데이터

### **IntroActivity**
> 용도: 로고 표시
<br>

### **LoginActivity**
> #### 용도: 로그인
> ※ 이미 로그인 되어있는 상태일 경우 LobbyActivity로 넘어감(SharedPreferences IS_LOGINED 컬럼 사용)
>
> 송신데이터 (외부서버)
>> 로그인
>> - ID, PW
>
> 수신데이터 (외부서버)
>> 로그인
>> - 로그인 성공 여부
>>   - 로그인 성공
>>   - 로그인 실패 - 아이디 없음
>>   - 로그인 실패 - 비밀번호 부적합
<br>

### **RegisterActivity**
>> #### 용도: 회원가입
>
> 송신데이터 (외부서버)
>> 회원가입
>> - ID, PW, 핸드폰번호, 실명
>
> 수신데이터 (외부서버)
>> 회원가입
>> - 회원가입 성공 여부
>>   - 회원가입 성공
>>   - 회원가입 실패 - 아이디 중복
<br>

### **QRRecognitionActivity**
> 용도: QR코드 인식창 표시
>
> 송신데이터 (POS)
>> - 사용자 핸드폰 번호
>
> 수신데이터 (POS)
>> 1) 매장정보
>> - 매장 이름, 매장 위치 
>> 2) 주문가능한 식품 목록
>> - 식품 이름, 가격,  카테고리, 이미지
<br>

### **LobbyActivity**
> 용도: 로그인 후 사용자 상태 및 기타 메뉴 표시
> ※ 통신 상태 유지(소켓 or Firebase 중 택 1)
>
> 수신데이터 (POS)
>> 1) 주문상태
>> - 미주문 상태
>> - 주문 접수 대기중
>> - 주문 완료
<br>

### **OrderListActivity**
> 용도: 주문내역 보기
>
> 수신데이터 (외부서버)
>> 1) 주문내역
>> - 매장 이름, 매장 위치, 상품 이름, 가격, 카테고리
<br>

### **SettingActivity**
> 용도: 설정 창
>> 1) 푸시 설정 (진동/소리, 팝업표시)
>> 2) 계정 관리 (비밀번호 변경, 휴대폰 번호 수정, 로그아웃, 탈퇴)
> 
>송신데이터(외부서버)
>> 1) 비밀번호 변경 요청
>> - 현재 비밀번호, 변경할 비밀번호
>> 2) 휴대폰 번호 수정 요청
>> - 수정할 휴대폰 번호
>> 3) 회원 탈퇴
>> - 계정 비밀번호
>
> 수신데이터(외부서버)
>> - 비밀번호 변경 성공
>> - 휴대폰 번호 수정 성공
>> - 회원 탈퇴 성공
<br>

### **CardActivity**
> 용도: 카드 등록 및 설정 화면
>
> 송신데이터 (외부서버)
>> 1) 카드 추가
>> - ID, 카드정보(카드번호, CVC, 비밀번호, 만기일)
>> 2) 카드 제거 요청
>> - 카드번호
>
> 수신데이터 (외부서버)
>> 1) 등록된 카드 정보
>> - 카드번호
>> 2) 카드 제거 성공
<br>

### **OrderingActivity**
> 용도: 식품 주문 화면
>
> 송신데이터 (CardActivity)
>> - 선택된 상품 정보
<br>

### **PayActivity**
> 용도: 결제방식 선택 및 결제정보 전송
>
> 송신데이터 (POS)
>> 1) 주문요청
>> - ID, 카드정보(카드번호, CVC, 비밀번호, 만기일), 주문정보(주문번호, 선택된 상품목록, 상품 개수) 
>> 2) 주문 취소 요청
>
> 수신데이터 (POS)
>> 1) 주문 결과
>> - true, false
>> 2) 주문 취소 결과
<br>

### **Background Service**
> 용도: POS기 푸시 알림 수신
>
> 수신데이터
>> - 주문 상태 및 정보
<br>

Activity 구성 및 Activity별 필요한 송수신 데이터 정리한 내용입니다. 확인 후 추가 수정사항 있으면 의견 달아주시기 바랍니다.

**Comment by westofsky** [comment]
Issue는 계속 Open 해놓고 Activity 별 진행 상황을 본문 각 Activity옆에다가 써놓으면 나중에 진행도 볼 때 편할거 같아요

**Comment by bapmukza9** [comment]
Issue는 계속 Open 해놓고 Activity 별 진행 상황을 본문 각 Activity옆에다가 써놓으면 나중에 진행도 볼 때 편할거 같아요

**Comment by ILoveGameCoding** [comment]
네. 프로토타입 완성 전까지 #11은 계속 수정하는 방향으로 하겠습니다.

**Comment by le-la** [comment]
디테일하게 잘 정리되어 있어서 따로 수정할 부분은 없어보입니다.

**Comment by ILoveGameCoding** [comment]
Activity에 대한 부분은 다른 이슈에서 정리하겠습니다
