### ISSUE TITLE
[U.O.F-Mobile] 디자인 추후 구현사항

### ISSUE THREAD

**Issue by westofsky** [UOF2021/U.O.F-Mobile#43]
## 추후 구현사항
> ### 디자인
>- **~~CardActivity와 AddCardDialog 디자인 구상~~**
>> 
>- **~~ChangePwDialog 디자인~~**
>> 
>- **~~LoginActivity에서 사용자 종류 선택 체크박스를 대체할 디자인 구상~~**
>> 
>- **~~Dialog에서 표시되는 문구 수정 필요~~**
>> 
>- **~~ChangePhoneDialog, ChangePwDialog, CheckPwDialog 내 TextInputLayout의 EditText 포맷 형식 설정 필요~~**

필요한 디자인 여기다가 적어주시면 추가하고 디자인 된 사항이 있는 경우 밑줄 표시하겠습니다.

**Comment by ILoveGameCoding** [comment]
- 앱 내 전체적인 색감 디자인이 필요
> 야간모드일 때와 아닐 때에 따라 Background, AppBar, Text, Button, Disable, Enable 등 다양한 상태에 해당하는 색을 themes.xml에 정의해서 사용해야 할 것 같습니다.

**Comment by ILoveGameCoding** [comment]
PayActivity 추가 디자인 필요
